travis:
  secure:
    BINSTAR_TOKEN: rd0bkGEuUt+gulXrh7EYF/TODd6ZqrqUFji01bX/HcunkSTFpemxXUzVTLBQ0kBOav8xHzZmFDoUTK6+dUd0M+/K79r6sm2LBbhAb8cuewbv4kRwwskAkqZWJ3zZEAt4OcuVDqVW6xnPxD/vWyF0Y0EPVWM/YxKgfsIr016ijGk6UXKjPjTi5QXZmuTyqZfHGli1EMFVTkDFjhBkoDmi+nPUO09lz5rePpWsjssDR25Jm81e9IYwqFQDf6gqdrBCrxQwdS8O53v1cUOpZ7gIog+cKeXsQkNH1fFcgu0n3WAT8706IGcPk4dD+KummjJ+XEMWmyzX3gNvrKPIbv+gQUKznhkwkThnl1jn3rAsyLPt4Drdy2veE6IS9fGe06Auqn00WDIgRP5y+kNi0qx04PboFzsN4ZTtcfxqSC/BZcZb+mJP3LyphZBa8yVYh96IEHLvWCeBZUL9e6GusnJPbtjHo+6Z9YTFLkLI06HD5NocD9KVj+IX8nVWPQyabUdBVlruWUFup3CQdpmowHxqagKks357T06qnV2H3Rbdwl6+q7DBCY6tQyaOIIJ6bukxAMdU3JSxMHCFEJwr/8GN/2TqClmHNn7EB56t1RnMhoOlXt/u+y2WxhJxJi1Y1/v7d14IC67axSv0giYzbTnbuDyF/69RSUR/kKhDebPb+HQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
