travis:
  secure:
    BINSTAR_TOKEN: tZ7Ja1RdhxDXImi8AeFnHGxmcFjoZz9RFfgvssny+CtnmJEmIiI9ygbhhGEO9daNYVZYEXsjpJMQLPabcNYUHcOwODOLaeGyNLwdQYu71FDLq/53D04bC8t/C2URfs5HuCTHS8U8+GfaecQl5CsU/dmLH3SVZdOP1BM7rRfqOW/m/z9alpiYjDs+qn4fUbb0VQhcxRx42pqnH176iuaiWMnW/SjyC9qfsH6gvRFb76Fo8lVNadMo0Y/oDudS3gnw4UoL9XszMvxrrz9wW25/ALnQrH9ttWbbawyVPc9Roy3JTQLp8o5X3egJX8LR8S8AkkwMYvmkoUdM8XUZVYLD8kn073vQSMAcpVFmfLswsTCVtu0IYu9bbiTQWvCyBTf1UjXbYpD+Rcr147Y7bkoNz0g8YGLp+/V6sdNQ2rjOMLly+fLNgaeuzS1pcncJjQqTc8rtxNKsTTtUexpDlYRn3tV3yr4O+k+n00Sn/bmW+xe4pbykSyLcspgdyy2XchB86b9elke1oNeea0HrNLrOIFh+84V9YhafZCy6v4MlCnT4STH3cQ6QNhCpR3NOBRs7Py0nfMjf1zQ7PTGpg6oJ40pYiF6gd5MUBZhbi6/LauZcZCoYUiiTXHd8La7tqL6cGApX3GEbWW23sJ/z4+KzwqQeXzFCi4LC6w4Txddul34=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
